Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 1300

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 8

# These are to compensate for some warnings that differ by
# rubocop/ruby version
Lint/UnneededDisable:
  Exclude:
    - 'lib/tfwrapper/raketasks.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/tfwrapper/version.rb'
    - 'spec/acceptance/acceptance_spec.rb'

Style/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/unit/raketasks_spec.rb'

# Offense count: 28
# Cop supports --auto-correct.
Style/Proc:
  Enabled: false
