# frozen_string_literal: true

require 'tfwrapper/raketasks'

TFWrapper::RakeTasks.install_tasks(
  'foo/bar',
  backend_config: {
    'path' => "terraform/testTwo/#{ENV['TFSUFFIX']}"
  },
  tf_vars_from_env: { 'foo' => 'FOO' },
  tf_extra_vars: { 'bar' => 'barval' }
)
