# frozen_string_literal: true

require 'tfwrapper/raketasks'

TFWrapper::RakeTasks.install_tasks(
  '.',
  namespace_prefix: 'default'
)

TFWrapper::RakeTasks.install_tasks(
  '.',
  namespace_prefix: 'disabled',
  disable_landscape: true
)

TFWrapper::RakeTasks.install_tasks(
  '.',
  namespace_prefix: 'stream',
  landscape_progress: :stream
)

TFWrapper::RakeTasks.install_tasks(
  '.',
  namespace_prefix: 'dots',
  landscape_progress: :dots
)

TFWrapper::RakeTasks.install_tasks(
  '.',
  namespace_prefix: 'lines',
  landscape_progress: :lines
)
